title: Charlotte Rice
description: TYPOGRAPHY
footer_text: Copyright 2021 Charlotte Rice
header_feature_image: ../uploads/tomatoes.jpg
header_text: My Typography Blog
header_text_color: "#ffffff"
bannerheight: 20vmax
navbarheight: 55px
logo: /uploads/logo.jpg
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
